# Logo
logo_image_source: https://s2.loli.net/2022/11/27/XIVQHhyJUReuP1a.png

# Index Page
index_banner_text: 欢迎来到 DragonOS
index_banner_text_secondary: 一个开源的操作系统
index_font_awesome_icon_css: fa fa-server

# Header
menu:
  首页: /
  文档: https://docs.dragonos.org
  联系我们: /contact
  赞助: /donate
  社区: https://bbs.DragonOS.org
  GitHub: https://github.com/fslongjin/DragonOS
  镜像站: https://mirrors.DragonOS.org
  关于: /about

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://s2.loli.net/2022/11/27/XIVQHhyJUReuP1a.png
about_widget_text: "DragonOS致力于成为一个完全独立自主的，具有Linux兼容性的，面向服务端的开源操作系统。"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  # - url: https://twitter.com/?lang=en
  #   fa_icon: fa-twitter
  # - url: https://www.facebook.com/
  #   fa_icon: fa-facebook
  # - url: https://dribbble.com/
  #   fa_icon: fa-dribbble 
  - url: https://github.com/fslongjin/dragonOS
    fa_icon: fa-github
  # - url: https://plus.google.com/
  #   fa_icon: fa-google-plus
  # - url: https://www.behance.net/
  #   fa_icon: fa-behance
  # - url: https://500px.com/
  #   fa_icon: fa-500px
  - url: mailto:longjin@RinGoTek.cn
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "©2015-2022 RinGoTek. All right reserved."
