# Logo
logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg

# Index Page
index_banner_text: 欢迎来到 DragonOS
index_banner_text_secondary: 一个开源的操作系统
index_font_awesome_icon_css: fa fa-server

# Header
menu:
  首页: /
  目录: /categories
  关于: /about
  联系我们: /contact
  归档: /archives

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tachyons.io/img/avatar_1.jpg
about_widget_text: "My name is LoGin and I want to produce something interesting for you!"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  # - url: https://twitter.com/?lang=en
  #   fa_icon: fa-twitter
  # - url: https://www.facebook.com/
  #   fa_icon: fa-facebook
  # - url: https://dribbble.com/
  #   fa_icon: fa-dribbble 
  - url: https://github.com/fslongjin/dragonOS
    fa_icon: fa-github
  # - url: https://plus.google.com/
  #   fa_icon: fa-google-plus
  # - url: https://www.behance.net/
  #   fa_icon: fa-behance
  # - url: https://500px.com/
  #   fa_icon: fa-500px
  - url: mailto:longjin@RinGoTek.cn
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "©2015-2021 RinGoTek. All right reserved."
